### ISSUE TITLE
Search async

### ISSUE THREAD

**Issue by Suplanus** [Genbox/Wikipedia#5]
Thanks for your great work 💕
Would love to see the Method `SearchAsync()`.

I think it would be easy to implement... this calls should be async:
- https://github.com/Genbox/WikipediaNet/blob/e466c8fe6c1329902267ccbdbb46346fc08ab293/src/WikipediaNet/Wikipedia.cs#L142
- https://github.com/Genbox/WikipediaNet/blob/e466c8fe6c1329902267ccbdbb46346fc08ab293/src/WikipediaNet/Wikipedia.cs#L173

**Comment by Genbox** [comment]
Hi. Sorry for the long delay, I've been tied up at work for a few months.

I'm currently working on Wolfram|Alpha API and rewriting it from scratch. Once I'm doing, I'll check out Wikipedia and see if I can't get the codebase into the 21st century.

**Comment by Suplanus** [comment]
Love to see this (both) 💕
