### ISSUE TITLE
Not working in Example Project 

### ISSUE THREAD

**Issue by BarisKarapelit** [Genbox/Wikipedia#6]
![Screenshot_1](https://user-images.githubusercontent.com/45313973/112740741-34420c00-8f88-11eb-91db-bfa1c91d6dfa.png)
![image](https://user-images.githubusercontent.com/45313973/112740755-4cb22680-8f88-11eb-879b-3774bbd5d08c.png)

**Comment by Genbox** [comment]
Cloned the project into a fresh folder, opened it in Visual Studio 2019, set the Examples project as startup and pressed CTRL + F5. This is the result:

![image](https://user-images.githubusercontent.com/657616/114303234-68134a80-9acd-11eb-997f-e20a2015cd9c.png)

Seems to work just fine.
